# Generated by Django 3.2 on 2023-04-22 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230421_1346'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='genretitle',
            name='unique_genre_title',
        ),
        migrations.AlterUniqueTogether(
            name='genretitle',
            unique_together={('genre_id', 'title_id')},
        ),
    ]
