# Generated by Django 3.2.3 on 2023-04-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20230416_1007'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='title',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='name_category'),
        ),
    ]
